# Generated by Django 3.2.13 on 2022-04-16 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', 'm0019_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerzoekenTeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uur_nummer', models.PositiveBigIntegerField(default=0)),
                ('teller', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
