# Generated by Django 4.2.7 on 2023-11-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wedstrijden', 'm0051_begrenzing_wereld'),
        ('Scheidsrechter', 'm0004_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheidsMutatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('mutatie', models.PositiveSmallIntegerField(default=0)),
                ('is_verwerkt', models.BooleanField(default=False)),
                ('door', models.CharField(default='', max_length=50)),
                ('wedstrijd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wedstrijden.wedstrijd')),
            ],
            options={
                'verbose_name': 'Scheids mutatie',
            },
        ),
    ]
