# -*- coding: utf-8 -*-

#  Copyright (c) 2023-2024 Ramon van der Winkel.
#  All rights reserved.
#  Licensed under BSD-3-Clause-Clear. See LICENSE file for details.

from BasisTypen.definities import SCHEIDS_BOND, SCHEIDS_INTERNATIONAAL, SCHEIDS_VERENIGING


SCHEIDS2LEVEL = {
    SCHEIDS_INTERNATIONAAL: 'SR5',
    SCHEIDS_BOND: 'SR4',
    SCHEIDS_VERENIGING: 'SR3'
}


BESCHIKBAAR_JA = 'J'
BESCHIKBAAR_NEE = 'N'
BESCHIKBAAR_DENK = 'D'
BESCHIKBAAR_LEEG = '?'

BESCHIKBAAR_CHOICES = (
    (BESCHIKBAAR_LEEG, "Niet ingevuld"),
    (BESCHIKBAAR_JA, "Ja"),
    (BESCHIKBAAR_DENK, "Onzeker"),
    (BESCHIKBAAR_NEE, "Nee"),
)

BESCHIKBAAR2STR = {
    BESCHIKBAAR_LEEG: "Niet ingevuld",
    BESCHIKBAAR_JA: "Ja",
    BESCHIKBAAR_DENK: "Onzeker",
    BESCHIKBAAR_NEE: "Nee",
}


SCHEIDS_MUTATIE_WEDSTRIJD_BESCHIKBAARHEID_OPVRAGEN = 1
SCHEIDS_MUTATIE_COMPETITIE_BESCHIKBAARHEID_OPVRAGEN = 3
SCHEIDS_MUTATIE_STUUR_NOTIFICATIES_WEDSTRIJD = 2
SCHEIDS_MUTATIE_STUUR_NOTIFICATIES_MATCH = 4
SCHEIDS_MUTATIE_REISTIJD_SR_BEPALEN = 5

SCHEIDS_MUTATIE_TO_STR = {
    SCHEIDS_MUTATIE_WEDSTRIJD_BESCHIKBAARHEID_OPVRAGEN: 'Beschikbaarheid wedstrijd opvragen',
    SCHEIDS_MUTATIE_COMPETITIE_BESCHIKBAARHEID_OPVRAGEN: 'Beschikbaarheid competitie opvragen',
    SCHEIDS_MUTATIE_STUUR_NOTIFICATIES_WEDSTRIJD: 'Stuur notificaties wedstrijd',
    SCHEIDS_MUTATIE_STUUR_NOTIFICATIES_MATCH: 'Stuur notificaties match',
    SCHEIDS_MUTATIE_REISTIJD_SR_BEPALEN: 'Reistijd scheidsrechters bepalen',
}


# end of file
