# Generated by Django 3.2.12 on 2022-04-10 08:48

from django.db import migrations, models
from django.utils import timezone
from decimal import Decimal


def verzamel_bestellingen(apps, _):
    """ verzamel de tot nu toe lossen MandjeInhoud regels in een MandjeBestelling """

    account_pk2bestelling = dict()      # [account.pk] = MandjeBestelling
    bestelling_pk2inhoud_pks = dict()   # [bestelling.pk] = [inhoud.pk, ...]

    inhoud_klas = apps.get_model('Mandje', 'MandjeProduct')
    bestelling_klas = apps.get_model('Mandje', 'MandjeBestelling')

    now = timezone.now()

    for inhoud in inhoud_klas.objects.select_related('account').all():      # pragma: no cover
        account_pk = inhoud.account.pk

        try:
            bestelling = account_pk2bestelling[account_pk]
        except KeyError:
            # nog geen bestelling aanwezig voor dit account
            bestelling = bestelling_klas(
                                account=inhoud.account,
                                aangemaakt=now,
                                totaal_euro=Decimal(0.0))
            bestelling.save()       # geen bulk, want het zijn er maar een paar
            account_pk2bestelling[account_pk] = bestelling
            bestelling_pk2inhoud_pks[bestelling.pk] = list()

        bestelling_pk2inhoud_pks[bestelling.pk].append(inhoud.pk)

        bestelling.totaal_euro += inhoud.prijs_euro
        bestelling.totaal_euro -= inhoud.korting_euro
    # for

    # koppel de producten aan elke bestelling
    for bestelling in account_pk2bestelling.values():
        bestelling.save()       # totaal_euro opslaan
        bestelling.producten.set(bestelling_pk2inhoud_pks[bestelling.pk])
    # for


class Migration(migrations.Migration):

    """ Migratie class voor dit deel van de applicatie """

    # volgorde afdwingen
    dependencies = [
        ('Account', 'm0019_squashed'),
        ('Kalender', 'm0013_code_uitgever'),
        ('Mandje', 'm0001_initial'),
    ]

    # migratie functies
    operations = [
        migrations.RenameModel(
            old_name='MandjeInhoud',
            new_name='MandjeProduct',
        ),
        migrations.AlterModelOptions(
            name='mandjeproduct',
            options={'verbose_name': 'Mandje product', 'verbose_name_plural': 'Mandje producten'},
        ),
        migrations.CreateModel(
            name='MandjeBestelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boekingsnummer', models.PositiveIntegerField(default=0)),
                ('aangemaakt', models.DateTimeField(auto_now=True)),
                ('totaal_euro', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('is_betaald', models.BooleanField(default=False)),
                ('wanneer_betaald', models.DateTimeField(default='2000-01-01T00:00:00+00:00')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='Account.account')),
                ('producten', models.ManyToManyField(to='Mandje.MandjeProduct')),
            ],
            options={
                'verbose_name': 'Mandje bestelling',
                'verbose_name_plural': 'Mandje bestellingen',
            },
        ),
        migrations.RunPython(verzamel_bestellingen),
    ]

# end of file
