# -*- coding: utf-8 -*-

#  Copyright (c) 2024 Ramon van der Winkel.
#  All rights reserved.
#  Licensed under BSD-3-Clause-Clear. See LICENSE file for details.

from Wedstrijden.definities import WEDSTRIJD_DISCIPLINE_OUTDOOR, WEDSTRIJD_DISCIPLINE_INDOOR, WEDSTRIJD_DISCIPLINE_VELD

# maxlength: 3
SPELD_CATEGORIE_WA_STER = "Ws"                      # Outdoor 1440
SPELD_CATEGORIE_WA_STER_ZILVER = "Wsz"
SPELD_CATEGORIE_WA_TARGET_AWARD = "Wt"
SPELD_CATEGORIE_WA_TARGET_AWARD_ZILVER = "Wtz"
SPELD_CATEGORIE_WA_ARROWHEAD = "Wa"                 # Veld
SPELD_CATEGORIE_NL_GRAADSPELD_INDOOR = "Ngi"
SPELD_CATEGORIE_NL_GRAADSPELD_OUTDOOR = "Ngo"
SPELD_CATEGORIE_NL_GRAADSPELD_VELD = "Ngv"
SPELD_CATEGORIE_NL_GRAADSPELD_SHORT_METRIC = "Ngs"
SPELD_CATEGORIE_NL_GRAADSPELD_ALGEMEEN = "Nga"
SPELD_CATEGORIE_NL_TUSSENSPELD = "Nt"

SPELD_CATEGORIE_CHOICES = [
    (SPELD_CATEGORIE_WA_STER, "WA ster"),
    (SPELD_CATEGORIE_WA_STER_ZILVER, "WA zilveren ster"),
    (SPELD_CATEGORIE_WA_TARGET_AWARD, "WA target award"),
    (SPELD_CATEGORIE_WA_TARGET_AWARD_ZILVER, "WA zilveren target award"),
    (SPELD_CATEGORIE_WA_ARROWHEAD, "WA arrowhead speld"),
    (SPELD_CATEGORIE_NL_GRAADSPELD_INDOOR, "NL graadspeld indoor"),
    (SPELD_CATEGORIE_NL_GRAADSPELD_OUTDOOR, "NL graadspeld outdoor"),
    (SPELD_CATEGORIE_NL_GRAADSPELD_VELD, "NL graadspeld veld"),
    (SPELD_CATEGORIE_NL_GRAADSPELD_SHORT_METRIC, "NL graadspeld short metric"),
    (SPELD_CATEGORIE_NL_GRAADSPELD_ALGEMEEN, "NL graadspeld algemeen"),
    (SPELD_CATEGORIE_NL_TUSSENSPELD, "NL tussenspeld"),
]


SOORT_BIJLAGE_SCOREBRIEFJE = 's'
SOORT_BIJLAGE_UITSLAG = 'u'

SOORT_BIJLAGE_CHOICES = [
    (SOORT_BIJLAGE_SCOREBRIEFJE, 'Scorebriefje'),
    (SOORT_BIJLAGE_UITSLAG, 'Uitslag'),
]


SOORT_BESTAND_FOTO = 'f'
SOORT_BESTAND_PDF = 'p'
SOORT_BESTAND_ONBEKEND = '?'

SOORT_BESTAND_CHOICES = [
    (SOORT_BESTAND_FOTO, 'Foto'),
    (SOORT_BESTAND_PDF, 'PDF'),
    (SOORT_BESTAND_ONBEKEND, '?'),
]


WEDSTRIJD_DISCIPLINE_CHOICES = [
    (WEDSTRIJD_DISCIPLINE_OUTDOOR, 'Outdoor'),
    (WEDSTRIJD_DISCIPLINE_INDOOR, 'Indoor'),        # Indoor = 18m/25m 3pijl
    (WEDSTRIJD_DISCIPLINE_VELD, 'Veld'),
]


# end of file
