# -*- coding: utf-8 -*-

#  Copyright (c) 2024 Ramon van der Winkel.
#  All rights reserved.
#  Licensed under BSD-3-Clause-Clear. See LICENSE file for details.

from Wedstrijden.definities import WEDSTRIJD_DISCIPLINE_OUTDOOR, WEDSTRIJD_DISCIPLINE_INDOOR, WEDSTRIJD_DISCIPLINE_VELD


SPELDSOORT_WA_STER = "Ws"                      # Outdoor 1440
SPELDSOORT_WA_TARGET_AWARD = "Wt"
SPELDSOORT_WA_ARROWHEAD = "Wa"                 # Veld
SPELDSOORT_NL_GRAADSPELD = "Ng"
SPELDSOORT_NL_GRAADSPELD_ALGEMEEN = "Na"
SPELDSOORT_NL_TUSSENSPELD = "Nt"

SPELDSOORT_CHOICES = [
    (SPELDSOORT_WA_STER, "WA ster"),
    (SPELDSOORT_WA_TARGET_AWARD, "WA Target award"),
    (SPELDSOORT_WA_ARROWHEAD, "WA arrowhead"),
    (SPELDSOORT_NL_GRAADSPELD, "NL graadspeld"),
    (SPELDSOORT_NL_GRAADSPELD_ALGEMEEN, "NL graadspeld algemeen"),
    (SPELDSOORT_NL_TUSSENSPELD, "NL tussenspeld"),
]


SOORT_BIJLAGE_SCOREBRIEFJE = 's'
SOORT_BIJLAGE_UITSLAG = 'u'

SOORT_BIJLAGE_CHOICES = [
    (SOORT_BIJLAGE_SCOREBRIEFJE, 'Scorebriefje'),
    (SOORT_BIJLAGE_UITSLAG, 'Uitslag'),
]


SOORT_BESTAND_FOTO = 'f'
SOORT_BESTAND_PDF = 'p'
SOORT_BESTAND_ONBEKEND = '?'

SOORT_BESTAND_CHOICES = [
    (SOORT_BESTAND_FOTO, 'Foto'),
    (SOORT_BESTAND_PDF, 'PDF'),
    (SOORT_BESTAND_ONBEKEND, '?'),
]


WEDSTRIJD_DISCIPLINE_CHOICES = [
    (WEDSTRIJD_DISCIPLINE_OUTDOOR, 'Outdoor'),
    (WEDSTRIJD_DISCIPLINE_INDOOR, 'Indoor'),        # Indoor = 18m/25m 3pijl
    (WEDSTRIJD_DISCIPLINE_VELD, 'Veld'),
]


# end of file
