# -*- coding: utf-8 -*-

#  Copyright (c) 2024-2026 Ramon van der Winkel.
#  All rights reserved.
#  Licensed under BSD-3-Clause-Clear. See LICENSE file for details.

from BasisTypen.definities import BOOGTYPE_AFKORTING_RECURVE, BOOGTYPE_AFKORTING_COMPOUND, BOOGTYPE_AFKORTING_BAREBOW

# maxlength: 4
SPELD_CATEGORIE_WA_STER_R = "Wsr"                       # Outdoor 1440
SPELD_CATEGORIE_WA_STER_ZILVER_R = "Wzsr"
SPELD_CATEGORIE_WA_STER_C = "Wsc"                       # Outdoor 1440
SPELD_CATEGORIE_WA_STER_ZILVER_C = "Wzsc"
SPELD_CATEGORIE_WA_TARGET_AWARD = "Wt"
SPELD_CATEGORIE_WA_TARGET_AWARD_ZILVER = "Wtz"
SPELD_CATEGORIE_WA_ARROWHEAD = "Wa"                     # Veld
SPELD_CATEGORIE_WA_ARROWHEAD_2024 = "Wa24"              # Veld sinds 2024
SPELD_CATEGORIE_WA_BEGINNER_AWARD = "Waba"
SPELD_CATEGORIE_NL_GRAADSPELD_INDOOR = "Ngi"
SPELD_CATEGORIE_NL_GRAADSPELD_OUTDOOR = "Ngo"
SPELD_CATEGORIE_NL_GRAADSPELD_VELD = "Ngv"
SPELD_CATEGORIE_NL_GRAADSPELD_SHORT_METRIC = "Ngs"
SPELD_CATEGORIE_NL_GRAADSPELD_ALGEMEEN = "Nga"
SPELD_CATEGORIE_NL_TUSSENSPELD = "Nt"

SPELD_CATEGORIE_CHOICES = [
    (SPELD_CATEGORIE_WA_STER_R, "WA ster recurve"),
    (SPELD_CATEGORIE_WA_STER_ZILVER_R, "WA zilveren ster recurve"),
    (SPELD_CATEGORIE_WA_STER_C, "WA ster compound"),
    (SPELD_CATEGORIE_WA_STER_ZILVER_C, "WA zilveren ster compound"),
    (SPELD_CATEGORIE_WA_TARGET_AWARD, "WA target award"),
    (SPELD_CATEGORIE_WA_TARGET_AWARD_ZILVER, "WA zilveren target award"),
    (SPELD_CATEGORIE_WA_ARROWHEAD, "WA arrowhead speld"),
    (SPELD_CATEGORIE_WA_ARROWHEAD_2024, "WA arrowhead 2024 speld"),
    (SPELD_CATEGORIE_WA_BEGINNER_AWARD, "WA beginner award"),
    (SPELD_CATEGORIE_NL_GRAADSPELD_INDOOR, "NL graadspeld indoor"),
    (SPELD_CATEGORIE_NL_GRAADSPELD_OUTDOOR, "NL graadspeld outdoor"),
    (SPELD_CATEGORIE_NL_GRAADSPELD_VELD, "NL graadspeld veld"),
    (SPELD_CATEGORIE_NL_GRAADSPELD_SHORT_METRIC, "NL graadspeld short metric"),
    (SPELD_CATEGORIE_NL_GRAADSPELD_ALGEMEEN, "NL graadspeld algemeen"),
    (SPELD_CATEGORIE_NL_TUSSENSPELD, "NL tussenspeld"),
]

SPELD_CATEGORIE2STR = {
    SPELD_CATEGORIE_WA_STER_R: "WA ster recurve",
    SPELD_CATEGORIE_WA_STER_ZILVER_R: "WA zilveren ster recurve",
    SPELD_CATEGORIE_WA_STER_C: "WA ster compound",
    SPELD_CATEGORIE_WA_STER_ZILVER_C: "WA zilveren ster compound",
    SPELD_CATEGORIE_WA_TARGET_AWARD: "WA target award",
    SPELD_CATEGORIE_WA_TARGET_AWARD_ZILVER: "WA zilveren target award",
    SPELD_CATEGORIE_WA_ARROWHEAD: "WA arrowhead speld",
    SPELD_CATEGORIE_WA_ARROWHEAD_2024: "WA arrowhead 2024 speld",
    SPELD_CATEGORIE_WA_BEGINNER_AWARD: "WA beginner award",
    SPELD_CATEGORIE_NL_GRAADSPELD_INDOOR: "NL graadspeld indoor",
    SPELD_CATEGORIE_NL_GRAADSPELD_OUTDOOR: "NL graadspeld outdoor",
    SPELD_CATEGORIE_NL_GRAADSPELD_VELD: "NL graadspeld veld",
    SPELD_CATEGORIE_NL_GRAADSPELD_SHORT_METRIC: "NL graadspeld short metric",
    SPELD_CATEGORIE_NL_GRAADSPELD_ALGEMEEN: "NL graadspeld algemeen",
    SPELD_CATEGORIE_NL_TUSSENSPELD: "NL tussenspeld",
}


SOORT_BIJLAGE_SCOREBRIEFJE = 's'
SOORT_BIJLAGE_UITSLAG = 'u'

SOORT_BIJLAGE_CHOICES = [
    (SOORT_BIJLAGE_SCOREBRIEFJE, 'Scorebriefje'),
    (SOORT_BIJLAGE_UITSLAG, 'Uitslag'),
]


SOORT_BESTAND_FOTO = 'f'
SOORT_BESTAND_PDF = 'p'
SOORT_BESTAND_ONBEKEND = '?'

SOORT_BESTAND_CHOICES = [
    (SOORT_BESTAND_FOTO, 'Foto'),
    (SOORT_BESTAND_PDF, 'PDF'),
    (SOORT_BESTAND_ONBEKEND, '?'),
]


SPELD_DISCIPLINE_OUTDOOR = 'OD'
SPELD_DISCIPLINE_INDOOR = 'IN'
SPELD_DISCIPLINE_VELD = 'VE'
SPELD_DISCIPLINE_NVT = 'XX'

SPELD_DISCIPLINE_CHOICES = [
    (SPELD_DISCIPLINE_OUTDOOR, 'Outdoor'),
    (SPELD_DISCIPLINE_INDOOR, 'Indoor'),        # Indoor = 18m/25m 3pijl
    (SPELD_DISCIPLINE_VELD, 'Veld'),
    (SPELD_DISCIPLINE_NVT, 'n.v.t.'),           # voor meesterspelden
]

SPELD_DISCIPLINE2STR = {
    SPELD_DISCIPLINE_OUTDOOR: 'Outdoor',
    SPELD_DISCIPLINE_INDOOR: 'Indoor',        # Indoor = 18m/25m 3pijl
    SPELD_DISCIPLINE_VELD: 'Veld',
    SPELD_DISCIPLINE_NVT: 'n.v.t.',           # voor meesterspelden
}


SPELD_BOOGTYPE_CHOICES = [
    (BOOGTYPE_AFKORTING_RECURVE, 'Recurve'),
    (BOOGTYPE_AFKORTING_COMPOUND, 'Compound'),
    (BOOGTYPE_AFKORTING_BAREBOW, 'Barebow'),
]


# end of file
