# Generated by Django 4.2.7 on 2023-12-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locatie', 'm0004_reistijd_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatie',
            name='adres_lat',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='locatie',
            name='adres_lon',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
