# -*- coding: utf-8 -*-

#  Copyright (c) 2022-2025 Ramon van der Winkel.
#  All rights reserved.
#  Licensed under BSD-3-Clause-Clear. See LICENSE file for details.

from BasisTypen.definities import SCHEIDS_BOND, SCHEIDS_VERENIGING, SCHEIDS_INTERNATIONAAL


OPLEIDING_STATUS_VOORBEREID = 'V'
OPLEIDING_STATUS_INSCHRIJVEN = 'I'
OPLEIDING_STATUS_GEANNULEERD = 'A'

OPLEIDING_STATUS_CHOICES = (
    (OPLEIDING_STATUS_VOORBEREID, 'Voorbereiden'),
    (OPLEIDING_STATUS_INSCHRIJVEN, 'Inschrijven'),
    (OPLEIDING_STATUS_GEANNULEERD, 'Geannuleerd'),
)

# opleidingscodes voor scheidsrechters
CODE_SR_VER = '040'
CODE_SR_BOND = '041'
CODE_SR_INTERNATIONAAL = '042'

CODE2SCHEIDS = {
    CODE_SR_VER: SCHEIDS_VERENIGING,
    CODE_SR_BOND: SCHEIDS_BOND,
    CODE_SR_INTERNATIONAAL: SCHEIDS_INTERNATIONAAL,
}

SCHEIDS2CODE = {
    SCHEIDS_VERENIGING: CODE_SR_VER,
    SCHEIDS_BOND: CODE_SR_BOND,
    SCHEIDS_INTERNATIONAAL: CODE_SR_INTERNATIONAAL,
}


# end of file
