# Generated by Django 3.1.7 on 2021-04-10 17:15

from django.db import migrations, models
import django.db.models.deletion


def migreer_wedstrijdplannen(apps, _):
    """ WedstrijdenPlan is nu CompetitieWedstrijdenPlan """

    plan_new_klas = apps.get_model('Wedstrijden', 'CompetitieWedstrijdenPlan')
    deelcomp_klas = apps.get_model('Competitie', 'DeelCompetitie')
    ronde_klas = apps.get_model('Competitie', 'DeelcompetitieRonde')

    old2new = dict()
    for plan_new in plan_new_klas.objects.prefetch_related('old').all():    # pragma: no cover
        old2new[plan_new.old.pk] = plan_new
    # for

    for deelcomp in deelcomp_klas.objects.exclude(plan=None).all():         # pragma: no cover
        plan_old_pk = deelcomp.plan.pk
        deelcomp.plan2 = old2new[plan_old_pk]
        deelcomp.save(update_fields=['plan2'])
    # for

    for ronde in ronde_klas.objects.exclude(plan=None).all():               # pragma: no cover
        plan_old_pk = ronde.plan.pk
        ronde.plan2 = old2new[plan_old_pk]
        ronde.save(update_fields=['plan2'])
    # for


class Migration(migrations.Migration):

    """ Migratie class voor dit deel van de applicatie """

    # volgorde afdwingen
    dependencies = [
        ('Competitie', 'm0037_renames_4'),
        ('Wedstrijden', 'm0014_renames_5'),
    ]

    # migratie functies
    operations = [
        migrations.AddField(
            model_name='deelcompetitie',
            name='plan2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Wedstrijden.competitiewedstrijdenplan'),
        ),
        migrations.AddField(
            model_name='deelcompetitieronde',
            name='plan2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Wedstrijden.competitiewedstrijdenplan'),
        ),
        migrations.RunPython(migreer_wedstrijdplannen)
    ]

# end of file
