# Generated by Django 3.2.13 on 2022-05-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Competitie', 'm0072_limiet_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampioenschapschutterboog',
            name='result_teamscore_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampioenschapschutterboog',
            name='result_teamscore_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampioenschapteam',
            name='result_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kampioenschapteam',
            name='result_teamscore',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
