# Generated by Django 4.0.8 on 2022-12-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    """ Migratie class voor dit deel van de applicatie """

    # volgorde afdwingen
    dependencies = [
        ('Competitie', 'm0081_kampioenschap_2'),
    ]

    # migratie functies
    operations = [
        migrations.AlterField(
            model_name='kampioenschapindivklasselimiet',
            name='deelcompetitie',
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, to='Competitie.deelcompetitie'),
        ),
        migrations.AlterField(
            model_name='kampioenschapindivklasselimiet',
            name='kampioenschap',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='Competitie.deelkampioenschap'),
        ),
        migrations.AlterField(
            model_name='kampioenschapsporterboog',
            name='deelcompetitie',
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, to='Competitie.deelcompetitie'),
        ),
        migrations.AlterField(
            model_name='kampioenschapsporterboog',
            name='kampioenschap',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='Competitie.deelkampioenschap'),
        ),
        migrations.AlterField(
            model_name='kampioenschapteam',
            name='deelcompetitie',
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, to='Competitie.deelcompetitie'),
        ),
        migrations.AlterField(
            model_name='kampioenschapteam',
            name='kampioenschap',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='Competitie.deelkampioenschap'),
        ),
        migrations.AlterField(
            model_name='kampioenschapteamklasselimiet',
            name='deelcompetitie',
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, to='Competitie.deelcompetitie'),
        ),
        migrations.AlterField(
            model_name='kampioenschapteamklasselimiet',
            name='kampioenschap',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='Competitie.deelkampioenschap'),
        ),
        migrations.RemoveField(
            model_name='deelkampioenschap',
            name='old_deelcomp',
        ),
        migrations.RemoveField(
            model_name='kampioenschapindivklasselimiet',
            name='deelcompetitie',
        ),
        migrations.RemoveField(
            model_name='kampioenschapsporterboog',
            name='deelcompetitie',
        ),
        migrations.RemoveField(
            model_name='kampioenschapteam',
            name='deelcompetitie',
        ),
        migrations.RemoveField(
            model_name='kampioenschapteamklasselimiet',
            name='deelcompetitie',
        ),
    ]

# end of file
