# Generated by Django 5.2.13 on 2026-05-09 19:36

import django.db.models.deletion
from django.db import migrations, models


def migreer_regio(apps, _):
    """ Migreer de database tabellen van Competitie naar CompLaagRegio """

    mutatie_klas = apps.get_model('Competitie', 'CompetitieMutatie')
    regiocomp_klas = apps.get_model('CompLaagRegio', 'RegioComp')

    regio_nr_afstand2regiocomp = dict()
    for regiocomp in regiocomp_klas.objects.select_related('competitie', 'regio').all():
        regio_nr = regiocomp.regio.regio_nr
        afstand = regiocomp.competitie.afstand
        tup = (regio_nr, afstand)
        regio_nr_afstand2regiocomp[tup] = regiocomp
    # for

    for mutatie in (mutatie_klas
                    .objects
                    .exclude(regiocompetitie=None)
                    .select_related('regiocompetitie',
                                    'regiocompetitie__competitie',
                                    'regiocompetitie__regio')
                    .all()):

        regio_nr = mutatie.regiocompetitie.regio.regio_nr
        afstand = mutatie.regiocompetitie.competitie.afstand
        tup = (regio_nr, afstand)
        regiocomp = regio_nr_afstand2regiocomp[tup]

        mutatie.regiocomp = regiocomp
        mutatie.save(update_fields=['regiocomp'])
    # for


class Migration(migrations.Migration):

    """ Migratie class voor dit deel van de applicatie """

    # volgorde afdwingen
    dependencies = [
        ('Competitie', 'm0123_kamp_migratie'),
    ]

    # migratie functies
    operations = [
        migrations.AddField(
            model_name='competitiemutatie',
            name='regiocomp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='CompLaagRegio.regiocomp'),
        ),
        migrations.RunPython(migreer_regio, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='competitiemutatie',
            name='regiocompetitie',
        ),
        migrations.RemoveField(
            model_name='regiocompetitieronde',
            name='regiocompetitie',
        ),
        migrations.RemoveField(
            model_name='regiocompetitiesporterboog',
            name='regiocompetitie',
        ),
        migrations.RemoveField(
            model_name='regiocompetitieteampoule',
            name='regiocompetitie',
        ),
        migrations.RemoveField(
            model_name='regiocompetitieteam',
            name='regiocompetitie',
        ),
        migrations.RemoveField(
            model_name='regiocompetitieronde',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='regiocompetitieronde',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='regiocompetitierondeteam',
            name='deelnemers_feitelijk',
        ),
        migrations.RemoveField(
            model_name='regiocompetitierondeteam',
            name='deelnemers_geselecteerd',
        ),
        migrations.RemoveField(
            model_name='regiocompetitierondeteam',
            name='scorehist_feitelijk',
        ),
        migrations.RemoveField(
            model_name='regiocompetitierondeteam',
            name='scores_feitelijk',
        ),
        migrations.RemoveField(
            model_name='regiocompetitierondeteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='regiocompetitiesporterboog',
            name='aangemeld_door',
        ),
        migrations.RemoveField(
            model_name='regiocompetitiesporterboog',
            name='bij_vereniging',
        ),
        migrations.RemoveField(
            model_name='regiocompetitiesporterboog',
            name='indiv_klasse',
        ),
        migrations.RemoveField(
            model_name='regiocompetitiesporterboog',
            name='inschrijf_gekozen_matches',
        ),
        migrations.RemoveField(
            model_name='regiocompetitiesporterboog',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='regiocompetitiesporterboog',
            name='sporterboog',
        ),
        migrations.RemoveField(
            model_name='regiocompetitieteam',
            name='leden',
        ),
        migrations.RemoveField(
            model_name='regiocompetitieteam',
            name='team_klasse',
        ),
        migrations.RemoveField(
            model_name='regiocompetitieteam',
            name='team_type',
        ),
        migrations.RemoveField(
            model_name='regiocompetitieteam',
            name='vereniging',
        ),
        migrations.RemoveField(
            model_name='regiocompetitieteampoule',
            name='teams',
        ),
        migrations.DeleteModel(
            name='Regiocompetitie',
        ),
        migrations.DeleteModel(
            name='RegiocompetitieRonde',
        ),
        migrations.DeleteModel(
            name='RegiocompetitieRondeTeam',
        ),
        migrations.DeleteModel(
            name='RegioCompetitieSporterBoog',
        ),
        migrations.DeleteModel(
            name='RegiocompetitieTeam',
        ),
        migrations.DeleteModel(
            name='RegiocompetitieTeamPoule',
        ),
    ]

# end of file
