# Generated by Django 4.2.15 on 2024-08-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betaal', 'm0018_pogingen'),
    ]

    operations = [
        migrations.AddField(
            model_name='betaaltransactie',
            name='bedrag_beschikbaar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='betaaltransactie',
            name='bedrag_te_ontvangen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='betaaltransactie',
            name='bedrag_terugbetaald',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='betaaltransactie',
            name='bedrag_teruggevorderd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='betaaltransactie',
            name='payment_status',
            field=models.CharField(default='', max_length=15),
        ),
    ]
