# -*- coding: utf-8 -*-

#  Copyright (c) 2024-2025 Ramon van der Winkel.
#  All rights reserved.
#  Licensed under BSD-3-Clause-Clear. See LICENSE file for details.


EVENEMENT_STATUS_ONTWERP = 'O'
EVENEMENT_STATUS_WACHT_OP_GOEDKEURING = 'W'
EVENEMENT_STATUS_GEACCEPTEERD = 'A'
EVENEMENT_STATUS_GEANNULEERD = 'X'

EVENEMENT_STATUS_CHOICES = (
    (EVENEMENT_STATUS_ONTWERP, 'Ontwerp'),
    (EVENEMENT_STATUS_WACHT_OP_GOEDKEURING, 'Wacht op goedkeuring'),
    (EVENEMENT_STATUS_GEACCEPTEERD, 'Geaccepteerd'),
    (EVENEMENT_STATUS_GEANNULEERD, 'Geannuleerd')
)

EVENEMENT_STATUS_TO_STR = {
    EVENEMENT_STATUS_ONTWERP: 'Ontwerp',
    EVENEMENT_STATUS_WACHT_OP_GOEDKEURING: 'Wacht op goedkeuring',
    EVENEMENT_STATUS_GEACCEPTEERD: 'Geaccepteerd',
    EVENEMENT_STATUS_GEANNULEERD: 'Geannuleerd'
}

EVENEMENT_INSCHRIJVING_STATUS_RESERVERING_MANDJE = 'R'        # moet nog omgezet worden in een bestelling
EVENEMENT_INSCHRIJVING_STATUS_BESTELD = 'B'                   # besteld; moet nog betaald worden
EVENEMENT_INSCHRIJVING_STATUS_DEFINITIEF = 'D'                # is betaald
EVENEMENT_INSCHRIJVING_STATUS_AFGEMELD = 'A'        # TODO: kan weg

EVENEMENT_INSCHRIJVING_STATUS_CHOICES = (
    (EVENEMENT_INSCHRIJVING_STATUS_RESERVERING_MANDJE, "Reservering"),
    (EVENEMENT_INSCHRIJVING_STATUS_BESTELD, "Besteld"),
    (EVENEMENT_INSCHRIJVING_STATUS_DEFINITIEF, "Definitief"),
    (EVENEMENT_INSCHRIJVING_STATUS_AFGEMELD, "Afgemeld"),
)

EVENEMENT_INSCHRIJVING_STATUS_TO_STR = {
    EVENEMENT_INSCHRIJVING_STATUS_RESERVERING_MANDJE: 'Gereserveerd, in mandje',
    EVENEMENT_INSCHRIJVING_STATUS_BESTELD: 'Gereserveerd, wacht op betaling',
    EVENEMENT_INSCHRIJVING_STATUS_DEFINITIEF: 'Inschrijving is definitief',
    EVENEMENT_INSCHRIJVING_STATUS_AFGEMELD: 'Afgemeld',
}

EVENEMENT_INSCHRIJVING_STATUS_TO_SHORT_STR = {
    EVENEMENT_INSCHRIJVING_STATUS_RESERVERING_MANDJE: 'In mandje',
    EVENEMENT_INSCHRIJVING_STATUS_BESTELD: 'Besteld',
    EVENEMENT_INSCHRIJVING_STATUS_DEFINITIEF: 'Definitief',
    EVENEMENT_INSCHRIJVING_STATUS_AFGEMELD: 'Afgemeld',
}


EVENEMENT_AFMELDING_STATUS_GEANNULEERD = 'C'      # bestelling geannuleerd voordat deze betaald werd
EVENEMENT_AFMELDING_STATUS_AFGEMELD = 'A'         # afgemeld nadat de betaling gedaan was
# FUTURE: restitutie

EVENEMENT_AFMELDING_STATUS_CHOICES = (
    (EVENEMENT_AFMELDING_STATUS_GEANNULEERD, 'Geannuleerd'),
    (EVENEMENT_AFMELDING_STATUS_AFGEMELD, 'Afgemeld'),
)

EVENEMENT_AFMELDING_STATUS_TO_STR = {
    EVENEMENT_AFMELDING_STATUS_GEANNULEERD: 'Geannuleerd',
    EVENEMENT_AFMELDING_STATUS_AFGEMELD: 'Afgemeld',
}

EVENEMENT_AFMELDING_STATUS_TO_SHORT_STR = {
    EVENEMENT_AFMELDING_STATUS_GEANNULEERD: 'Geannuleerd',
    EVENEMENT_AFMELDING_STATUS_AFGEMELD: 'Afgemeld',
}


EVENEMENT_BEGRENZING_STR = 'KHSN leden + gast-accounts'


# end of file
