# -*- coding: utf-8 -*-

#  Copyright (c) 2024 Ramon van der Winkel.
#  All rights reserved.
#  Licensed under BSD-3-Clause-Clear. See LICENSE file for details.


EVENEMENT_STATUS_ONTWERP = 'O'
EVENEMENT_STATUS_WACHT_OP_GOEDKEURING = 'W'
EVENEMENT_STATUS_GEACCEPTEERD = 'A'
EVENEMENT_STATUS_GEANNULEERD = 'X'

EVENEMENT_STATUS_CHOICES = (
    (EVENEMENT_STATUS_ONTWERP, 'Ontwerp'),
    (EVENEMENT_STATUS_WACHT_OP_GOEDKEURING, 'Wacht op goedkeuring'),
    (EVENEMENT_STATUS_GEACCEPTEERD, 'Geaccepteerd'),
    (EVENEMENT_STATUS_GEANNULEERD, 'Geannuleerd')
)

EVENEMENT_STATUS_TO_STR = {
    EVENEMENT_STATUS_ONTWERP: 'Ontwerp',
    EVENEMENT_STATUS_WACHT_OP_GOEDKEURING: 'Wacht op goedkeuring',
    EVENEMENT_STATUS_GEACCEPTEERD: 'Geaccepteerd',
    EVENEMENT_STATUS_GEANNULEERD: 'Geannuleerd'
}

EVENEMENTINSCHRIJVING_STATUS_RESERVERING_MANDJE = 'R'        # moet nog omgezet worden in een bestelling
EVENEMENTINSCHRIJVING_STATUS_RESERVERING_BESTELD = 'B'       # moet nog betaald worden
EVENEMENTINSCHRIJVING_STATUS_DEFINITIEF = 'D'                # is betaald
EVENEMENTINSCHRIJVING_STATUS_AFGEMELD = 'A'
EVENEMENTINSCHRIJVING_STATUS_VERWIJDERD = 'V'                # handmatig of automatisch uit mandje verwijderd

EVENEMENTINSCHRIJVING_STATUS_CHOICES = (
    (EVENEMENTINSCHRIJVING_STATUS_RESERVERING_MANDJE, "Reservering"),
    (EVENEMENTINSCHRIJVING_STATUS_RESERVERING_BESTELD, "Besteld"),
    (EVENEMENTINSCHRIJVING_STATUS_DEFINITIEF, "Definitief"),
    (EVENEMENTINSCHRIJVING_STATUS_AFGEMELD, "Afgemeld"),
    (EVENEMENTINSCHRIJVING_STATUS_VERWIJDERD, "Verwijderd"),
)

EVENEMENTINSCHRIJVING_STATUS_TO_STR = {
    EVENEMENTINSCHRIJVING_STATUS_RESERVERING_MANDJE: 'Gereserveerd, in mandje',
    EVENEMENTINSCHRIJVING_STATUS_RESERVERING_BESTELD: 'Gereserveerd, wacht op betaling',
    EVENEMENTINSCHRIJVING_STATUS_DEFINITIEF: 'Inschrijving is definitief',
    EVENEMENTINSCHRIJVING_STATUS_AFGEMELD: 'Afgemeld',
    EVENEMENTINSCHRIJVING_STATUS_VERWIJDERD: 'Verwijderd',
}

EVENEMENTINSCHRIJVING_STATUS_TO_SHORT_STR = {
    EVENEMENTINSCHRIJVING_STATUS_RESERVERING_MANDJE: 'In mandje',
    EVENEMENTINSCHRIJVING_STATUS_RESERVERING_BESTELD: 'Besteld',
    EVENEMENTINSCHRIJVING_STATUS_DEFINITIEF: 'Definitief',
    EVENEMENTINSCHRIJVING_STATUS_AFGEMELD: 'Afgemeld',
    EVENEMENTINSCHRIJVING_STATUS_VERWIJDERD: 'Verwijderd',
}


# end of file
