# -*- coding: utf-8 -*-

#  Copyright (c) 2022-2025 Ramon van der Winkel.
#  All rights reserved.
#  Licensed under BSD-3-Clause-Clear. See LICENSE file for details.

from BasisTypen.definities import SCHEIDS_BOND, SCHEIDS_VERENIGING, SCHEIDS_INTERNATIONAAL


OPLEIDING_STATUS_VOORBEREID = 'V'
OPLEIDING_STATUS_INSCHRIJVEN = 'I'
OPLEIDING_STATUS_GEANNULEERD = 'A'
OPLEIDING_STATUS_GESLOTEN = 'G'

OPLEIDING_STATUS_CHOICES = (
    (OPLEIDING_STATUS_VOORBEREID, 'Voorbereiden'),
    (OPLEIDING_STATUS_INSCHRIJVEN, 'Inschrijven'),
    (OPLEIDING_STATUS_GESLOTEN, 'Inschrijving gesloten'),
    (OPLEIDING_STATUS_GEANNULEERD, 'Geannuleerd'),
)

OPLEIDING_STATUS_TO_STR = {
    OPLEIDING_STATUS_VOORBEREID: 'Voorbereiden',
    OPLEIDING_STATUS_INSCHRIJVEN: 'Inschrijven',
    OPLEIDING_STATUS_GESLOTEN: 'Inschrijving gesloten',
    OPLEIDING_STATUS_GEANNULEERD: 'Geannuleerd',
}

# opleidingscodes voor scheidsrechters
CODE_SR_VER = '040'
CODE_SR_BOND = '041'
CODE_SR_INTERNATIONAAL = '042'

CODE2SCHEIDS = {
    CODE_SR_VER: SCHEIDS_VERENIGING,
    CODE_SR_BOND: SCHEIDS_BOND,
    CODE_SR_INTERNATIONAAL: SCHEIDS_INTERNATIONAAL,
}

SCHEIDS2CODE = {
    SCHEIDS_VERENIGING: CODE_SR_VER,
    SCHEIDS_BOND: CODE_SR_BOND,
    SCHEIDS_INTERNATIONAAL: CODE_SR_INTERNATIONAAL,
}


OPLEIDING_INSCHRIJVING_STATUS_INSCHRIJVEN = 'I'               # invoer van alle gegevens; nog niet in mandje
OPLEIDING_INSCHRIJVING_STATUS_RESERVERING_MANDJE = 'R'        # in mandje; moet nog omgezet worden in een bestelling
OPLEIDING_INSCHRIJVING_STATUS_BESTELD = 'B'                   # besteld; moet nog betaald worden
OPLEIDING_INSCHRIJVING_STATUS_DEFINITIEF = 'D'                # bestelling is betaald

OPLEIDING_INSCHRIJVING_STATUS_CHOICES = (
    (OPLEIDING_INSCHRIJVING_STATUS_INSCHRIJVEN, "Inschrijven"),
    (OPLEIDING_INSCHRIJVING_STATUS_RESERVERING_MANDJE, "Reservering"),
    (OPLEIDING_INSCHRIJVING_STATUS_BESTELD, "Besteld"),
    (OPLEIDING_INSCHRIJVING_STATUS_DEFINITIEF, "Definitief"),
)

OPLEIDING_INSCHRIJVING_STATUS_TO_STR = {
    OPLEIDING_INSCHRIJVING_STATUS_INSCHRIJVEN: 'Inschrijven',
    OPLEIDING_INSCHRIJVING_STATUS_RESERVERING_MANDJE: 'Gereserveerd, in mandje',
    OPLEIDING_INSCHRIJVING_STATUS_BESTELD: 'Gereserveerd, wacht op betaling',
    OPLEIDING_INSCHRIJVING_STATUS_DEFINITIEF: 'Inschrijving is definitief',
}

OPLEIDING_INSCHRIJVING_STATUS_TO_SHORT_STR = {
    OPLEIDING_INSCHRIJVING_STATUS_INSCHRIJVEN: 'Inschrijven',
    OPLEIDING_INSCHRIJVING_STATUS_RESERVERING_MANDJE: 'In mandje',
    OPLEIDING_INSCHRIJVING_STATUS_BESTELD: 'Besteld',
    OPLEIDING_INSCHRIJVING_STATUS_DEFINITIEF: 'Definitief',
}


OPLEIDING_AFMELDING_STATUS_GEANNULEERD = 'C'      # bestelling geannuleerd voordat deze betaald werd
OPLEIDING_AFMELDING_STATUS_AFGEMELD = 'A'         # afgemeld nadat de betaling gedaan was
# FUTURE: restitutie

OPLEIDING_AFMELDING_STATUS_CHOICES = (
    (OPLEIDING_AFMELDING_STATUS_GEANNULEERD, 'Geannuleerd'),
    (OPLEIDING_AFMELDING_STATUS_AFGEMELD, 'Afgemeld'),
)

OPLEIDING_AFMELDING_STATUS_TO_STR = {
    OPLEIDING_AFMELDING_STATUS_GEANNULEERD: 'Geannuleerd',
    OPLEIDING_AFMELDING_STATUS_AFGEMELD: 'Afgemeld',
}

OPLEIDING_AFMELDING_STATUS_TO_SHORT_STR = {
    OPLEIDING_AFMELDING_STATUS_GEANNULEERD: 'Geannuleerd',
    OPLEIDING_AFMELDING_STATUS_AFGEMELD: 'Afgemeld',
}

# end of file
